name: Deploy landing page

on:
  release:
    types: [ published ]

env:
  ENVIRONMENT: prod
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_REPOSITORY: ${{ vars.REGISTRY }}/${{ vars.ORGANIZATION }}/${{ github.event.repository.name }}
  APP_VERSION: ${{ github.event.release.tag_name }}
  HOST: ${{ vars.HOST }}


jobs:
  build-and-push:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build and Push image with Docker buildx
        uses: IsItgone/ci-templates/.github/actions/build-and-push-image@main
        with:
          registry: ${{ vars.REGISTRY }}
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.APP_VERSION }}
          password: ${{ secrets.GHCR_TOKEN }}


  update-helm-chart:
    needs: build-and-push
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.ORGANIZATION }}/cluster-config
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update Helm Chart
        working-directory: apps/${{ env.REPOSITORY_NAME }}/${{ env.ENVIRONMENT }}/chart
        run: |
          yq -i '.appVersion = "${{ env.APP_VERSION }}"' Chart.yaml
          yq -i '.flutter-base.image.repository = "${{ env.IMAGE_REPOSITORY }}"' values.yaml
          yq -i '.flutter-base.image.tag = "${{ env.APP_VERSION }}"' values.yaml
          yq -i '.flutter-base.ingress.host = "${{ env.HOST }}"' values.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Image tag to ${{ env.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}